# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

locale                   : "en-GB"
title                    : "Abu Siddique"
title_separator          : "|"
name                     : &name "Abu Siddique"
description              : &description "Associate Professor of Economics, Department of Economics, Royal Holloway University of London. Development, health, gender, and political economy."
url                      : "https://absidd-que.github.io"
baseurl                  : ""
repository               : "abubsiddque/abubsiddque.github.io"
google_scholar_stats_use_cdn: true
masthead_title           : " "

# -----------------------------------------------------------------------------
# Author / Sidebar
# -----------------------------------------------------------------------------

author:
  avatar           : "profile.jpg"  


# -----------------------------------------------------------------------------
# Build settings
# -----------------------------------------------------------------------------

include:
  - .htaccess
  - _pages

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope: { path: "", type: pages }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: publications }
    values: { layout: single, author_profile: true, share: false }
  - scope: { path: "", type: teaching }
    values: { layout: single, author_profile: true, share: false }
  - scope: { path: "", type: talks }
    values: { layout: single, author_profile: true, share: false }

sass:
  sass_dir: _sass
  style: compressed

permalink: /:title/
timezone: Europe/London
